name: careerfix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Calibri
      fonts:
        - asset: assets/font/FontsFree-Net-calibri-regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family:   
      fonts:
        - asset: assets\font\Cambria-Font-For Android.ttf

